{
 "title": "Ak Bars Call Center",
 "time": { "from": "2016-12-10T18:38:47.429Z", "to": "2018-05-08T13:41:36.267Z" },
 "templating": {
  "list": [
   {
    "name": "LastMetricTime",
    "label": "LastMetricTiem",
    "query": "SELECT LAST(\"time2\") FROM calls_in"
   },
   { "name": "confidence", "label": "conf", "query": "20" }
  ]
 },
 "panels": [
  {
   "title": "Потерянные звонки",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "calls_lost",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Обработанные звонки",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "calls_proc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "content": "![805369264085152.jpg](http://s0.rbk.ru/rbcplus_pics/resized/1180xH/media/img/2/15/805369264085152.jpg)\n"
  },
  {
   "title": "Количество звонков в день",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Количество входящих звонков",
     "measurement": "calls_in",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Предсказания",
     "measurement": "calls_in_predictions",
     "select": [
      [
       { "params": [ "prediction" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Нижняя граница",
     "measurement": "calls_in_predictions",
     "select": [
      [
       { "params": [ "lowbound" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Верхняя граница",
     "measurement": "calls_in_predictions",
     "select": [
      [
       { "params": [ "upbound" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Planned Feature", "type": "text", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 }, "content": "# It Will be Cool" }
 ]
}